export const ADD_NEW_ITEM_INIT = 'ADD_NEW_ITEM_INIT';
export const ADD_NEW_ITEM_FINISHED = 'ADD_NEW_ITEM_FINISHED';
export const FETCH_PALLETS_INIT = 'FETCH_PALLETS_INIT';
export const FETCH_PALLETS_SUCCESS = 'FETCH_PALLETS_SUCCESS';
export const DELETE_ITEM_INIT = 'DELETE_ITEM_INIT';
export const EDIT_ITEM_INIT = 'EDIT_ITEM_INIT';
export const EDIT_ITEM_FINISHED = 'EDIT_ITEM_FINISHED';

export const FETCH_SORTING_DATA_INIT = 'FETCH_SORTING_DATA_INIT';
export const FETCH_SORTING_DATA_SUCCESS = 'FETCH_SORTING_DATA_SUCCESS';
export const ADD_NEW_SORTING_INIT = 'ADD_NEW_SORTING_INIT';
export const ADD_SORTING_FINISHED = 'ADD_SORTING_FINISHED';
export const FETCH_AVAILABLE_PALLETS_SUCCESS = 'FETCH_AVAILABLE_PALLETS_SUCCESS';