export const ADD_NEW_ITEM_INIT = 'ADD_NEW_ITEM_INIT';
export const ADD_NEW_ITEM_FINISHED = 'ADD_NEW_ITEM_FINISHED';
export const FETCH_PALLETS_INIT = 'FETCH_PALLETS_INIT';
export const FETCH_PALLETS_SUCCESS = 'FETCH_PALLETS_SUCCESS';
export const DELETE_ITEM_INIT = 'DELETE_ITEM_INIT';